//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traga_Cervejas
{
    using System;
    using System.Collections.Generic;
    
    public partial class jogo
    {
        public int id { get; set; }
        public string jogador { get; set; }
        public int pontos { get; set; }
        public Nullable<System.DateTime> dia { get; set; }
    }
}
